# Introduction to Python Programming

Welcome to this beginner-friendly tutorial on Python programming! Python is a powerful and versatile programming language that is widely used in various fields, including web development, data science, artificial intelligence, and more. In this tutorial, we'll cover the basics of Python and equip you with the essential knowledge to start your journey as a Python programmer.

## Why Learn Python?

Python is an excellent choice for beginners due to its simple and readable syntax, making it easy to understand and write code. It emphasizes code readability, which means developers can express their ideas with fewer lines of code compared to other programming languages. Additionally, Python has a vast community and extensive libraries that offer a wide range of functionalities, making it a go-to language for many developers.

## What Will You Learn?

In this tutorial, we'll cover the following fundamental topics of Python programming:

1. **Variables and Data Types**: Understand how to declare variables and work with different data types, such as numbers, strings, lists, tuples, and dictionaries.

2. **Control Flow**: Learn about conditional statements (if-else), loops (for and while), and how to control the flow of your program.

3. **Functions**: Explore how to define and use functions to modularize your code and make it more organized.

4. **Input and Output**: Learn how to interact with users by taking input and displaying output.

5. **File Handling**: Discover how to read and write files using Python.

6. **Exception Handling**: Understand how to handle errors and exceptions in your code gracefully.

By the end of this tutorial, you'll have a solid foundation in Python programming and be ready to tackle more advanced topics or explore specific areas of interest.

## Prerequisites

This tutorial assumes you have no prior experience with Python or programming. However, a basic understanding of programming concepts will be helpful. All you need is a computer with Python installed, and you're good to go!

Let's get started on this exciting journey of learning Python programming!



## Table of Contents

- [Data_Types_Structures](#Data_Types_Structures) 
  - [Variables](#Variables)
    - [Declaring Variables](#Declaring-Variables)
    - [Variables Types](#Variables-Types)
  - [Data_Structures](#Data_Structures)
    - [Lists](#Lists)
    - [Dictionaries](#Dictionaries)
    - [Tuples](#Tuples)
    - [Sets](#Sets)
    - [NumPy Arrays](#NumPy-Arrays)
    - [Pandas DataFrames](#Pandas-DataFrames)
    - [Tensors](#Tensors)
- [FLow_Control_Statements](#FLow_Control_Statements)
  - ["for" loop](#"for"-loop)
  - ["while" loop](#"while"-loop)
  - [Conditional Judgment Statement](#Conditional-Judgment-Statement)
  - [Control Statements: break and continue](#Control-Statements:-break-and-continue)
- [Operations: Methods, Functions](#Operations_Methods_Functions)
  - [Methods](#Methods)
  - [Define function](#Define_function)
- [Class](#Class)

## Data_Types_Structures

### Variables

In Python, a variable is a name that refers to a value stored in the computer's memory. Variables are used to store data that can be later accessed and manipulated in the program. Python is a dynamically typed language, which means you don't need to declare the data type of a variable explicitly; Python will determine the type based on the assigned value.

#### Declaring Variables

To create a variable in Python, you simply need to assign a value to a name using the assignment operator `=`. Here's the general syntax:

```python
variable_name = value
```

#### Variables Types

As mentioned earlier, Python is dynamically typed, so you can assign different types of values to the same variable. Some common variable types in Python are:

- Integer: Whole numbers, e.g., age = 25
- Float: Decimal numbers, e.g., price = 12.99
- String: Textual data, e.g., name = "John"
- Boolean: Represents True or False, e.g., is_student = True

In [1]:
# int
var = 1
print(var)
print(type(var))

1
<class 'int'>


In [2]:
# float
var = 1.
print(var)
print(type(var))

1.0
<class 'float'>


In [3]:
# string
var = '1'
print(var)
print(type(var))

1
<class 'str'>


In [4]:
# boolean
var = bool(1)
print(var)
print(type(var))

True
<class 'bool'>


### Data_Structures

Data structures are fundamental tools in computer programming that allow you to organize and store data in a way that facilitates efficient operations. Python provides several built-in data structures that cater to different needs and scenarios. In this introduction, we'll explore some of the most commonly used data structures in Python.


#### Lists

A list is a versatile and ordered collection of elements, represented by square brackets `[ ]`. Lists can store different types of data, such as numbers, strings, and even other lists. You can add, remove, or modify elements in a list easily.

```Python
numbers = [1, 2, 3, 4, 5]
fruits = ["apple", "banana", "orange"]
mixed_list = [1, "hello", True, 3.14]
```

In [5]:
# list
data_struct = [1, 2., '3']
print(data_struct)
print(type(data_struct))
print('\n')

# add an element to list
data_struct.append(10)
print('The list after adding an element is:')
print(data_struct)
print('\n')

# extend list
print('The list after extending itself is:')
data_struct.extend(data_struct)
print(data_struct)

[1, 2.0, '3']
<class 'list'>


The list after adding an element is:
[1, 2.0, '3', 10]


The list after extending itself is:
[1, 2.0, '3', 10, 1, 2.0, '3', 10]


#### Dictionaries

Dictionaries are unordered collections that store data in key-value pairs, represented by curly braces { }. Each value in a dictionary is associated with a unique key, which allows for fast and efficient data retrieval.

```python
person = {"name": "John", "age": 30, "city": "New York"}
book = {"title": "Python Programming", "author": "Jane Doe", "year": 2022}
```

In [6]:
# dict
data_struct = {'integer':1, 'string':'2', 'float_num':3.}
print('The dict is:')
print(data_struct)
print('\n')
print('The data type is:')
print(type(data_struct))
print('\n')

# add item to dict
print('The dict after adding a list is:')
data_struct['list'] = [1, 2, 3]
print(data_struct)

The dict is:
{'integer': 1, 'string': '2', 'float_num': 3.0}


The data type is:
<class 'dict'>


The dict after adding a list is:
{'integer': 1, 'string': '2', 'float_num': 3.0, 'list': [1, 2, 3]}


#### Tuples

Tuples are similar to lists but are immutable, meaning their elements **cannot be changed** after creation. Tuples are represented by parentheses ( ).

```Python
point = (10, 20)
colors = ("red", "green", "blue")
```

In [2]:
# Representing RGB colors (Red, Green, Blue) in a tuple
red_color = (255, 0, 0)
green_color = (0, 255, 0)
blue_color = (0, 0, 255)

# Defining constants using tuples
PI = (3.14159265359,)
GRAVITY = (9.81,)

print(PI)

(3.14159265359,)


#### Sets

Sets are unordered collections of unique elements, represented by curly braces { }. Sets **do not allow duplicate values**, making them useful for eliminating duplicates from a list.

```Python
numbers_set = {1, 2, 3, 4, 5}
letters_set = {"a", "b", "c"}
```

In [5]:
# Creating a set of unique elements
fruits = {"apple", "banana", "orange", "apple", "grape"}
unique_fruits = set(fruits)

# Creating a set of unique elements using {}
numbers = {1, 2, 3, 3, 4, 4, 5, 5}


print('unique number:',numbers)
print('fruits_sets:',fruits)

unique number: {1, 2, 3, 4, 5}
fruits_sets: {'orange', 'grape', 'banana', 'apple'}


#### Installing the numpy package: 


The easiest way to install NumPy is to use the pip tool. You just need to run the following command line

In [1]:
!pip install numpy

Looking in indexes: http://mirrors.aliyun.com/pypi/simple/


#### NumPy Arrays

NumPy (Numerical Python) is a powerful library in Python for numerical computations. One of the key features of NumPy is the ability to work with arrays efficiently. A NumPy array is a multi-dimensional, homogeneous data structure that allows you to store and manipulate large amounts of data efficiently.


NumPy arrays offer several advantages over Python lists:

1. **Efficiency**: NumPy arrays are implemented in C and provide highly efficient numerical operations, making them faster than traditional Python lists, especially for large datasets.

2. **Multi-dimensional Support**: NumPy arrays can have multiple dimensions, allowing you to represent complex data such as images, audio signals, and more.

3. **Broadcasting**: NumPy arrays support broadcasting, which simplifies operations on arrays with different shapes, making code concise and readable.

4. **Mathematical Functions**: NumPy provides a wide range of mathematical functions and operations that are optimized for arrays.

5. **Interoperability**: NumPy arrays can interact seamlessly with other libraries in the scientific Python ecosystem, making it a core component of data analysis and scientific computing.

##### Creating NumPy Arrays

To use NumPy, you need to install it first (if you use Python with anaconda, the package has been ready and you don't have to do it). You can install it using pip:

```Python
pip install numpy
```

Once installed, you can import NumPy and create arrays as follows:

```Python
import numpy as np

# Create a 1D array
arr1d = np.array([1, 2, 3, 4, 5])

# Create a 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Create an empty array
empty_arr = np.empty((3, 3))

# Create an array with all zeros
zeros_arr = np.zeros((2, 4))

# Create an array with all ones
ones_arr = np.ones((3, 2))
```

In [2]:
# array
import numpy as np
arr1d = np.array([1, 2, 3, 4, 5])
data_struct = np.array([[1, 2, 3], [4, 5, 6]])
print('The array is:')
print(data_struct)
print('\n')
print('The data type is:')
print(type(data_struct))
print('\n')

# access the shape of array
print('The shape of the array')
print(data_struct.shape)
print('\n')

# matrix transpose
print('The transposed array is:')
print(data_struct.T)
print('\n')

# matrix multiplication
print('Matrix multiplication example result:')
print(data_struct @ data_struct.T)
print('\n')

#element-wise product of arrays
print('Matrix multiplication example result:')
print(data_struct * data_struct)

The array is:
[[1 2 3]
 [4 5 6]]


The data type is:
<class 'numpy.ndarray'>


The shape of the array
(2, 3)


The transposed array is:
[[1 4]
 [2 5]
 [3 6]]


Matrix multiplication example result:
[[14 32]
 [32 77]]


Matrix multiplication example result:
[[ 1  4  9]
 [16 25 36]]


You can access elements in a NumPy array using indexing, just like in Python lists:

In [13]:
# Accessing elements in a 1D array
print('The first element in a 1D array:',arr1d[0])  # Output: 1

# Accessing elements in a 2D array
print('The element with row 2 and column 3 in a 2D array:',data_struct[1, 2])  # Output: 6


The first element in a 1D array: 1
The element with row 2 and column 3 in a 2D array: 6


You can also use slicing to extract specific portions of the array:

Slicing is a powerful technique in Python that allows you to extract specific portions of an array or sequence. In the context of arrays, slicing enables you to access a subset of elements based on their indices. This makes it easy to retrieve and work with specific segments of data efficiently.

The syntax for slicing an array is as follows, and the item with **start** index is inclusive, whereas the item with **stop** index is exclusive (it should be noted that the array index **starts at 0**):

```python
array[start:stop:step]
```

Some code demo can be seen as follows:

```Python
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Slice elements from index 2 to index 5 (exclusive)
slice1 = numbers[2:5]  # Output: [3, 4, 5]

# Slice elements from index 0 to index 8 with a step of 2
slice2 = numbers[0:8:2]  # Output: [1, 3, 5, 7]

# Slice elements from the beginning to index 5 (exclusive)
slice3 = numbers[:5]  # Output: [1, 2, 3, 4, 5]

# Slice elements from index 5 to the end
slice4 = numbers[5:]  # Output: [6, 7, 8, 9, 10]

# Slice elements in reverse order
slice5 = numbers[::-1]  # Output: [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
```

You can use negative indices for slicing as well. Negative indices count from the end of the array:

```python
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Slice elements from index -3 to the end
slice6 = numbers[-3:]  # Output: [8, 9, 10]

# Slice elements from index -5 to index -2 (exclusive)
slice7 = numbers[-5:-2]  # Output: [6, 7, 8]
```

In [18]:
# Slicing a 1D array
print('The second item to the fifth item in a 1D array:',arr1d[1:4])  # Output: [2, 3, 4]

# Slicing a 2D array
print('The first to the third in row, and the second to the last in column:','\n',data_struct[:2, 1:])  # Output: [[2, 3], [5, 6]]

The second item to the fifth item in a 1D array: [2 3 4]
The first to the third in row, and the second to the last in column: 
 [[2 3]
 [5 6]]


#### Installing pandas and ohter packages

The easiest way to install pandas and ohter packages is to use the pip tool. You just need to run the following command line


In [3]:
!pip install pandas
!pip install scikit-learn

Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/


#### Pandas DataFrames

DataFrames are a key data structure in Python's Pandas library, designed for handling and analyzing tabular data efficiently. A DataFrame is a 2-dimensional, labeled data structure, similar to a spreadsheet or SQL table, where data is arranged in rows and columns.


DataFrames offer several advantages for data manipulation and analysis:

1. **Tabular Representation**: DataFrames provide a tabular and organized way to represent data, making it easy to understand and work with structured datasets.

2. **Data Cleaning and Transformation**: DataFrames enable you to clean, preprocess, and transform data effectively using powerful methods and functions.

3. **Easy Indexing**: DataFrames support both row and column indexing, making it convenient to access and modify specific data points.

4. **Alignment and Broadcasting**: DataFrames automatically align data during operations, and Pandas supports broadcasting, which simplifies computations on data with different shapes.

5. **Integration with Other Libraries**: DataFrames seamlessly integrate with other Python libraries, making it a crucial tool for data analysis and manipulation.

##### Creating DataFrames

To use DataFrames, you need to install the Pandas library first (if you use Python with anaconda, the package has been ready and you don't have to do it). You can install it using pip:

```Python
pip install pandas
```

Once installed, you can import Pandas and create DataFrames as follows:

```Python
import pandas as pd

# Create a DataFrame from a dictionary
data = {'Name': ['John', 'Alice', 'Bob'],
        'Age': [25, 30, 28],
        'City': ['New York', 'San Francisco', 'Chicago']}

df = pd.DataFrame(data)

# Create a DataFrame from a CSV file
df_from_csv = pd.read_csv('data.csv')
```

In [3]:
# DataFrame
import pandas as pd
array = np.array([[1, 2, 3], [4, 5, 6]])
print('The DataFrame is:')
data_struct = pd.DataFrame(array, index=['row1', 'row2'], columns=['column1', 'column2', 'column3'])
print(data_struct)
print('\n')

# Create a DataFrame from a dict
data = {
    'Name': ['John', 'Alice', 'Bob'],
    'Age': [25, 30, 28],
    'City': ['New York', 'San Francisco', 'Chicago']
}

df = pd.DataFrame(data)

# Display the DataFrame
print("DataFrame:")
print(df)
print()

# Accessing columns
print("Accessing columns:")
print(df['Name'])
print()

# Adding a new column
df['Gender'] = ['Male', 'Female', 'Male']

# Dropping a column
df.drop('City', axis=1, inplace=True)

# Display the modified DataFrame
print("Modified DataFrame:")
print(df)
print()

# Slicing rows
print("Slicing rows:")
print(df[1:3])
print()

# Filtering rows based on conditions
young_people = df[df['Age'] < 30]
print("Young people:")
print(young_people)

# detailed pandas quick tutorials can be found at
# https://pandas.pydata.org/docs/user_guide/10min.html#min

The DataFrame is:
      column1  column2  column3
row1        1        2        3
row2        4        5        6


DataFrame:
    Name  Age           City
0   John   25       New York
1  Alice   30  San Francisco
2    Bob   28        Chicago

Accessing columns:
0     John
1    Alice
2      Bob
Name: Name, dtype: object

Modified DataFrame:
    Name  Age  Gender
0   John   25    Male
1  Alice   30  Female
2    Bob   28    Male

Slicing rows:
    Name  Age  Gender
1  Alice   30  Female
2    Bob   28    Male

Young people:
   Name  Age Gender
0  John   25   Male
2   Bob   28   Male


#### Tensors

Tensors are a fundamental data structure in deep learning and scientific computing. They are multi-dimensional arrays that enable efficient numerical computations and form the foundation for building and training deep learning models. PyTorch, a popular deep learning library, relies heavily on tensors for its operations.

Tensors offer several advantages for numerical computations and deep learning:

1. **Efficient Numerical Operations**: Tensors are optimized for numerical operations and provide fast computation, especially when working with large datasets.

2. **GPU Acceleration**: PyTorch supports GPU acceleration, allowing for even faster tensor computations, essential for training large neural networks.

3. **Automatic Differentiation**: PyTorch's `autograd` feature enables automatic differentiation, making it easy to compute gradients for training deep learning models.

4. **Flexible Data Representation**: Tensors can represent data of varying dimensions, from scalars (0-dimensional tensors) to multi-dimensional arrays.

5. **Easy Integration with Deep Learning**: PyTorch's tensor operations are designed to work seamlessly with neural network architectures.

##### Creating Tensors

To use tensors in Python, you need to install the PyTorch library first. You can install it using pip:

```Python
pip install torch
```

Once installed, you can import PyTorch and create tensors as follows:

```python
import torch

# Create a 0-dimensional tensor (scalar)
scalar_tensor = torch.tensor(3.14)

# Create a 1-dimensional tensor (vector)
vector_tensor = torch.tensor([1, 2, 3, 4, 5])

# Create a 2-dimensional tensor (matrix)
matrix_tensor = torch.tensor([[1, 2], [3, 4], [5, 6]])

# Create a 3-dimensional tensor
tensor_3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
```

For those who are new to Python, we recommend starting with the basics of Python programming before diving into PyTorch tensors. Understanding Python fundamentals will lay a strong foundation for your future journey into deep learning. In this tutorial, we'll first cover the essentials of Python, including variables, data types, control flow, functions, and more. Once you feel comfortable with Python, we'll introduce you to the powerful world of PyTorch tensors, a key data structure in deep learning. Don't worry if tensors seem challenging at first; they will become clearer as you progress. Our goal is to help you build confidence in Python programming, preparing you for exciting adventures in the field of deep learning later on.


In [2]:
# tensor
# you can skip this code frame at this stage
import torch
import numpy as np
print('The tensor is:')
array = np.array([[1, 2, 3], [4, 5, 6]])
data_struct = torch.tensor(array)
print(data_struct)
#print('\n')

# detailed pytorch quick tutorials can be found at
# https://pytorch.org/tutorials/

The tensor is:
tensor([[1, 2, 3],
        [4, 5, 6]])


## FLow_Control_Statements

### "for" loop

A "for loop" is a fundamental control structure in Python that allows you to iterate over a sequence of elements, such as a list, tuple, string, or range, and perform certain actions for each element. For loops are powerful and versatile, making them essential for repetitive tasks and data processing.

#### Basics For Loop Syntax

The syntax for a for loop in Python is as follows:

```python
for element in sequence:
    print(element)
```

```python
# Example 1: Looping through a list
fruits = ["apple", "banana", "orange", "grape"]

for fruit in fruits:
    print(fruit)

#Output:
# apple
# banana
# orange
# grape

# Example 2: Looping through a string
message = "Hello, World!"

for char in message:
    print(char)

# Output:
# H
# e
# l
# l
# o
# ,
#  
# W
# o
# r
# l
# d
# !

# Example 3: Looping through a range of numbers
for num in range(1, 6):
    print(num)

# Output:
# 1
# 2
# 3
# 4
# 5

```

In [10]:
max_num_iter = 5  # the maximum number of iteration

# "i" is a temporary variable to use in each iteration
# "range" is a build-in function to generate iterable values
for i in range(max_num_iter):
    print(i)
# Note: the index number in Python starts from 0, not 1!


0
1
2
3
4


In [11]:
for i in range(2, 7):
    print(i)
# Note that the starting point of range(x, y)
# is included but the ending point is not
# (x is included but y is excluded)

2
3
4
5
6


In [12]:
# "for" loop and list
test_list = []  # create an empty list
print('list before adding value is', test_list)
for i in range(5):
    test_list.append(i)

print('list after adding value is', test_list)

list before adding value is []
list after adding value is [0, 1, 2, 3, 4]


### "while" loop

A "while loop" is a fundamental control structure in Python that allows you to repeatedly execute a block of code as long as a certain condition is true. While loops are used when the number of iterations is not known beforehand and the loop continues until the condition becomes false.

#### Basic While Loop Syntax

The syntax for a while loop in Python is as follows:

```python
while condition:
    # Code block to be executed while the condition is true
```

```python
# Example: Printing numbers from 1 to 5 using a while loop
num = 1

while num <= 5:
    print(num)
    num += 1

# Output:
# 1
# 2
# 3
# 4
# 5

```

In [13]:
# in "while" loop, an iterable variable must be pre-specified
c = 0
while c<5:
    print(c)
    c = c + 1

# Personally, "for" loop is more used than "while" loop

0
1
2
3
4


### Conditional Judgment Statement

In Python, the `if-else` statement is used to make decisions in your code based on certain conditions. It allows you to execute different blocks of code depending on whether a given condition is true or false.

#### Basic Syntax:

The basic syntax of the `if-else` statement is as follows:

```python
if condition:
    # Code block to be executed if the condition is true
else:
    # Code block to be executed if the condition is false
```

- The `condition` is an expression that evaluates to either `True` or `False`.
- If the `condition` is true, the code block under the `if` statement is executed.
- If the `condition` is false, the code block under the `else` statement (if present) is executed.

#### Nested `if-else`:

You can also use nested if-else statements to handle more complex conditions. This means having an if statement inside another if or else block. This allows you to check multiple conditions sequentially. The demo is as follows:

```python
# Input marks from the user
marks = int(input("Enter your marks: "))

# Check grade based on marks
if marks >= 90:
    print("Grade: A")
elif marks >= 80:
    print("Grade: B")
elif marks >= 70:
    print("Grade: C")
elif marks >= 60:
    print("Grade: D")
else:
    print("Grade: F")
```

- In this example, we use the if-elif-else statement to determine the grade based on the input marks. Depending on the value of marks, the code will execute the corresponding block and print the associated grade.

In [6]:
# Input number from the user
num = int(input("Enter a number: "))

# Check if the number is positive or negative
if num > 0:
    print("The number is positive.")
else:
    print("The number is negative.")

Enter a number:  1


The number is positive.


In [7]:
# Input month from the user
month = int(input("Enter the month (1-12): "))

# Determine the season based on the month
if month in [3, 4, 5]:
    season = "Spring"
elif month in [6, 7, 8]:
    season = "Summer"
elif month in [9, 10, 11]:
    season = "Autumn/Fall"
else:
    season = "Winter"

print("The season is:", season)

Enter the month (1-12):  3


The season is: Spring


### Control Statements: break and continue

You can use the **break** statement to exit a while loop prematurely and the **continue** statement to skip the rest of the current iteration and move to the next one

```python
# Example: Using break and continue in a while loop
num = 1

while num <= 10:
    if num == 5:
        break  # Exit the loop when num is 5
    if num % 2 == 0:
        num += 1
        continue  # Skip even numbers and move to the next iteration
    print(num)
    num += 1

# Output:
# 1
# 3
# 7
# 9

```

In [4]:
# Example: Skipping specific values using continue in a while loop
num = 1

while num <= 10:
    if num == 5:
        num += 1
        continue  # Skip number 5 and move to the next iteration
    print(num)
    num += 1

1
2
3
4
6
7
8
9
10


In [5]:
# Example: Finding the first occurrence of a number using a while loop
numbers = [2, 4, 7, 6, 8, 10]
target = 6
index = 0

while index < len(numbers):
    if numbers[index] == target:
        print(f"Found {target} at index {index}.")
        break
    index += 1

Found 6 at index 3.


## Operations_Methods_Functions

### Methods

In Python, a method is a function that is associated with an object. It can be called on that object and can access the data within the object. Methods are defined within the class, and they perform specific actions or operations related to the object's state.

Example Method: `split`

```python
# Define a sample string
sentence = "Hello, how are you today?"

# Use the split() method to split the string by whitespace
words = sentence.split()

# Print the result
print(words)  # Output: ['Hello,', 'how', 'are', 'you', 'today?']
```

- In this example, the split() method is called on the sentence string, and it splits the string into a list of words based on the default separator, which is whitespace.
- A method is associated with a specific object, meaning that methods that work for one object may not work for other objects.
- There are many methods in Python, and you can call them to complete some tasks easily like the following examlples
- You can also define method in a **class**, which will be introduced later.

In [14]:
print('append is a method')
test_list = []
test_list.append(1)
print(test_list)

append is a method
[1]


In [15]:
print('There is no output for a method:')
test_list = []
print(test_list.append(1))

There is no output for a method:
None


In [16]:
print('sum is a function')
test_list = [1, 2, 3]
summation = sum(test_list)
print(summation)

sum is a function
6


In [17]:
# now we try to sort the DataFrame by the first column
# by descending order
print('pd.sort_values is a function')
test_df = pd.DataFrame(array, index=['row1', 'row2'], columns=['column1', 'column2', 'column3'])

print(test_df.sort_values(by='column1', ascending=False))
print('\n')

# apply sort_values
test_df.sort_values(by='column1', ascending=False)
print('If no value assignment, the original DataFrame remains unchanged', '\n', test_df)
print('\n')

# The correct approach is to assign the sorted DataFrame to itself
print('The DataFrame is now sorted!')
test_df = test_df.sort_values(by='column1', ascending=False)
print(test_df)


pd.sort_values is a function
      column1  column2  column3
row2        4        5        6
row1        1        2        3


If no value assignment, the original DataFrame remains unchanged 
       column1  column2  column3
row1        1        2        3
row2        4        5        6


The DataFrame is now sorted!
      column1  column2  column3
row2        4        5        6
row1        1        2        3


### Define_function

Functions are a fundamental concept in Python that allow you to encapsulate a block of code into a reusable unit. Defining functions helps in modularizing your code, making it easier to read, maintain, and debug. Functions enable you to break down complex tasks into smaller, manageable parts, promoting code reusability and reducing redundancy.

#### Basic Function Syntax

The syntax for defining a function in Python is as follows:

```python
def function_name(parameters):
    # Code block to be executed when the function is called
    # Optionally, the function can return a value using the 'return' statement
```
- function_name: The name of the function, which you choose to identify and call the function.
- parameters: The input arguments (if any) that the function takes. These are variables used to pass data to the function.
- return: An optional statement that returns a value from the function to the caller. If omitted, the function returns **None**.

Example 1:
```python
def greet(name):
    return f"Hello, {name}! Welcome to the Python world."

# Call the function
message = greet("Alice")
print(message)

# Output:
# Hello, Alice! Welcome to the Python world.
```

- In this example, we defined a function named **greet** that takes a single parameter name. The function returns a greeting message that includes the provided name. When we call the function with "Alice" as an argument, it returns the personalized greeting, which we store in the variable message and then print.

Example 2 (Function with Default Parameters):

- You can also define functions with default parameters. Default parameters are assigned a value if no value is provided when calling the function.

```python
def greet(name="Guest"):
    return f"Hello, {name}! Welcome to the Python world."

# Call the function without providing an argument
message = greet()
print(message)

# Output:
# Hello, Guest! Welcome to the Python world.
```

- In this example, the greet function has a default parameter name="Guest". If we call the function without providing any argument, it will use the default value and greet the "Guest."

In [9]:
def my_function(input1, input2):
    # write your funciton details here
    # consider both inputs are numerical values (int, float)
    output = input1 + input2
    return output

In [10]:
my_function(1, 2) #return the addition

3

## Class

In Python, a class is a blueprint for creating objects. It allows you to define your own custom data types with attributes (variables) and methods (functions) that operate on those attributes. Classes provide a way to organize and encapsulate data and behavior, making code more organized, reusable, and maintainable.

#### Basic Syntax

```python
class ClassName:
    def __init__(self, parameter1, parameter2, ...):
        # Constructor method to initialize attributes
        self.attribute1 = parameter1
        self.attribute2 = parameter2
        # ...

    def method1(self, arg1, arg2, ...):
        # Method 1 code here
        # ...

    def method2(self, arg1, arg2, ...):
        # Method 2 code here
        # ...
```

- The `class` keyword is used to define a new class followed by the ClassName.
- The `__init__` method (constructor) is called when an object of the class is created. It initializes the object's attributes with the given parameters.
- `self` is a reference to the instance of the class and is automatically passed as the first argument to the methods within the class.
- You can define additional methods within the class like `method1` and `method2`, which operate on the class's attributes.

A simple clss of Person is shown below:

```python
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def say_hello(self):
        return f"Hello, my name is {self.name} and I am {self.age} years old."

# Create an instance of the Person class
person1 = Person("Alice", 30)

# Call the say_hello method
message = person1.say_hello()
print(message)  # Output: Hello, my name is Alice and I am 30 years old.
```

- In this example, we define the `Person` class with the `__init__` method to initialize the `name` and `age` attributes. We also have a method called `say_hello` that returns a greeting with the person's name and age. We then create an instance of the `Person` class and call the `say_hello` method on that instance.

#### Inheritance

Python supports inheritance, allowing you to create a new class that inherits the attributes and methods from an existing class. This promotes code reusability and allows you to create specialized classes based on a more general class.

```python
class Student(Person):
    def __init__(self, name, age, student_id):
        super().__init__(name, age)
        self.student_id = student_id

    def display_student_info(self):
        return f"Student: {self.name}, Age: {self.age}, ID: {self.student_id}"

# Create an instance of the Student class
student1 = Student("Bob", 22, "12345")

# Call the say_hello method inherited from the Person class
print(student1.say_hello())  # Output: Hello, my name is Bob and I am 22 years old.

# Call the display_student_info method
print(student1.display_student_info())  # Output: Student: Bob, Age: 22, ID: 12345
```

In this example, we create a `Student` class that inherits from the `Person` class. The Student class has an additional attribute `student_id` and a new method `display_student_info`. `The super()` function is used to call the constructor of the parent class, ensuring that the `name` and `age` attributes are initialized correctly.

In [11]:
# Define the base class 'Vehicle'
class Vehicle:
    def __init__(self, brand, model, year):
        self.brand = brand
        self.model = model
        self.year = year

    def display_info(self):
        return f"{self.year} {self.brand} {self.model}"

# Define a subclass 'Car' that inherits from 'Vehicle'
class Car(Vehicle):
    def __init__(self, brand, model, year, num_doors):
        # Call the constructor of the base class using super()
        super().__init__(brand, model, year)
        self.num_doors = num_doors

    def display_info(self):
        # Override the display_info method to include the number of doors
        return f"{self.year} {self.brand} {self.model} ({self.num_doors} doors)"

In [12]:
# Define another subclass 'Motorcycle' that also inherits from 'Vehicle'
class Motorcycle(Vehicle):
    def __init__(self, brand, model, year, num_wheels):
        # Call the constructor of the base class using super()
        super().__init__(brand, model, year)
        self.num_wheels = num_wheels

    def display_info(self):
        # Override the display_info method to include the number of wheels
        return f"{self.year} {self.brand} {self.model} ({self.num_wheels} wheels)"

In [13]:
# Create instances of the subclasses
car1 = Car("Toyota", "Corolla", 2022, 4)
motorcycle1 = Motorcycle("Harley Davidson", "Sportster", 2021, 2)

# Display information about the vehicles
print(car1.display_info())          # Output: 2022 Toyota Corolla (4 doors)
print(motorcycle1.display_info())   # Output: 2021 Harley Davidson Sportster (2 wheels)

2022 Toyota Corolla (4 doors)
2021 Harley Davidson Sportster (2 wheels)
